apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackjack-frontend
  namespace: default
  annotations:
    kapp.k14s.io/update-strategy: fallback-on-replace
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: blackjack
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/component: run
    carto.run/workload-name: blackjack-frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: run
      app.kubernetes.io/part-of: blackjack
      apps.tanzu.vmware.com/has-tests: "true"
      apps.tanzu.vmware.com/workload-type: server
      carto.run/workload-name: blackjack-frontend
  template:
    metadata:
      annotations:
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: blackjack
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: server
        carto.run/workload-name: blackjack-frontend
    spec:
      containers:
      - env:
        - name: AMQP_HOSTNAME
          valueFrom:
            secretKeyRef:
              key: host
              name: edge-inferencing-events-default-user
              optional: true
        - name: AMQP_PORT
          valueFrom:
            secretKeyRef:
              key: port
              name: edge-inferencing-events-default-user
              optional: true
        - name: AMQP_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: edge-inferencing-events-default-user
              optional: true
        - name: AMQP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: edge-inferencing-events-default-user
              optional: true
        image: harbor.services.edge.wrightcode.io:9443/apps/blackjack-frontend-wrightmi@sha256:237ac6f2586baa83e7b8777f5244ddf260ec57b21b8a9a90aae3e0841393f695
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default
---
apiVersion: v1
kind: Service
metadata:
  name: blackjack-frontend
  namespace: default
  labels:
    app.kubernetes.io/part-of: blackjack
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/component: run
    carto.run/workload-name: blackjack-frontend
spec:
  selector:
    app.kubernetes.io/component: run
    app.kubernetes.io/part-of: blackjack
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: server
    carto.run/workload-name: blackjack-frontend
  ports:
  - targetPort: 8080
    port: 8080
    name: http
  type: NodePort
