apiVersion: apps/v1
kind: Deployment
metadata:
  name: computer-vision-inferencing-app
  namespace: default
  annotations:
    kapp.k14s.io/update-strategy: fallback-on-replace
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: blackjack-backend
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/component: run
    carto.run/workload-name: computer-vision-inferencing-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: run
      app.kubernetes.io/part-of: blackjack-backend
      apps.tanzu.vmware.com/has-tests: "true"
      apps.tanzu.vmware.com/workload-type: server
      carto.run/workload-name: computer-vision-inferencing-app
  template:
    metadata:
      annotations:
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: blackjack-backend
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: server
        carto.run/workload-name: computer-vision-inferencing-app
    spec:
      containers:
      - env:
        - name: RMQ_EXCHANGE
          value: "cv-exchange"
        - name: RMQ_VHOST
          value: "edge-vhost"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: ACCELERATION_DEVICE
          value: GPU
        - name: INFERENCING_MODEL
          value: models/quantized_cards_detect-1023
        - name: INFERENCE_URL
          value: http://engine-svc:8080
        - name: AMQP_HOSTNAME
          valueFrom:
            secretKeyRef:
              key: host
              name: edge-inferencing-events-default-user
              optional: true
        - name: AMQP_PORT
          valueFrom:
            secretKeyRef:
              name: edge-inferencing-events-default-user
              key: port
              optional: true
        - name: AMQP_USER
          valueFrom:
            secretKeyRef:
              name: edge-inferencing-events-default-user
              key: username
              optional: true
        - name: AMQP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: edge-inferencing-events-default-user
              key: password
              optional: true
        - name: VIDEO_INPUT
          valueFrom:
            secretKeyRef:
              name: source-info
              key: video-source
              optional: true
        # image: harbor.services.edge.wrightcode.io:9443/apps/computer-vision-inferencing-app-wrightmi@sha256:526a1d36931887ce5afa35a52b8258f93e92bda147fc7fbbf100564b9c8a22d4
        image: mwrightpivotal/wallaroo_detect:v0.1
        name: workload
        resources:
          limits:
            gpu.intel.com/i915: "1"
        securityContext:
          runAsUser: 0
      serviceAccountName: default
---
apiVersion: v1
kind: Service
metadata:
  name: computer-vision-inferencing-app
  namespace: default
  labels:
    app.kubernetes.io/part-of: blackjack-backend
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/component: run
    carto.run/workload-name: computer-vision-inferencing-app
spec:
  selector:
    app.kubernetes.io/component: run
    app.kubernetes.io/part-of: blackjack-backend
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: server
    carto.run/workload-name: computer-vision-inferencing-app
  ports:
  - targetPort: 8080
    port: 8080
    name: http

