# Used for engine imagePullSecret

apiVersion: v1
kind: Secret
metadata:
  name: oci-registry-docker
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "makeSecret.dockerconfigjson" . }}

---

# Same info but mounted in engine fieldwise

apiVersion: v1
kind: Secret
metadata:
  name: oci-registry
type: Opaque
data:
  USERNAME: {{ .Values.ociRegistry.username | toString | b64enc | quote }}
  PASSWORD: {{ .Values.ociRegistry.password | toString | b64enc | quote }}
  URI: {{ .Values.ociRegistry.registry | toString | b64enc | quote }}


# User input checks

{{ if not .Values.ociRegistry.username }}
{{ fail "ociRegistry username must be provided" }}
{{ end }}

{{ if not .Values.ociRegistry.password }}
{{ fail "ociRegistry password must be provided" }}
{{ end }}
  
{{ if not .Values.ociRegistry.registry }}
{{ fail "ociRegistry registry must be provided" }}
{{ end }}
