---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: yolo8demonstration-card
  namespace: default
spec:
  type: "oci"
  interval: 1m0s
  url: oci://harbor.services.edge.wrightcode.io:9443/wallaroo/charts/yolo8demonstration-card
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: backend
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: yolo8demonstration-card
      version: "0.0.1-24903487-a8e2-4b41-a9e5-8ae43bc522cb"
      sourceRef:
        kind: HelmRepository
        name: yolo8demonstration-card
        namespace: default
      interval: 1m
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: true
  values:
    ociRegistry:
      username: admin
      password: dummy
