---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: yolo8demonstration-card
  namespace: default
spec:
  type: "oci"
  interval: 1m0s
  url: oci://harbor.services.edge.wrightcode.io/wallaroo/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: backend
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: yolo8demonstration-card
      version: "0.0.1-24903487-a8e2-4b41-a9e5-8ae43bc522cb"
      sourceRef:
        kind: HelmRepository
        name: yolo8demonstration-card
        namespace: default
      interval: 1m
  upgrade:
    remediation:
      remediateLastFailure: true
  install:
    remediation:
      retries: -1
  test:
    enable: true
  values:
    engine:
      pipelineUrl: harbor.services.edge.wrightcode.io/wallaroo/pipelines/yolo8demonstration-card@sha256:05da537385588121d2ece139f4bedee301d0e48c2707920fbeaf51b887ed6acb
    ociRegistry:
      username: admin
      password: dummy
      registry: "harbor.services.edge.wrightcode.io"
    image: 
      repository: harbor.services.edge.wrightcode.io/wallaroo/engines/proxy/wallaroo/ghcr.io/wallaroolabs/standalone-mini
